In [1]:
# Place %autoreload 2 at the top of your notebook to ensure it applies to all subsequent imports.
%load_ext autoreload
%autoreload 2
 


In [2]:
from __future__ import absolute_import, division, print_function
import torch
from trainer_end_to_end import Trainer
from options import MonodepthOptions
import time
options = MonodepthOptions()
args = [
    '--data_path', '/mnt/nct-zfs/TCO-All/SharedDatasets/SCARED_Images_Resized/',
    # '--of_samples_num', '3', 
    '--batch_size', '10', 
    # '--log_frequency', '2',
    # '--log_dir', '/mnt/nct-zfs/TCO-Test/jinjingxu/exps/train/mvp3r/results/debug_reloc3r_backbone/relocxr',
    '--debug',
    ]
opts = options.parse_notebook(args)# trainer.set_eval()
# opts
opts.dataset

2025-09-12 21:37:20.289551: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1757705840.302779 2393174 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757705840.306791 2393174 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1757705840.317117 2393174 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757705840.317134 2393174 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757705840.317135 2393174 computation_placer.cc:177] computation placer alr

Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead


'endovis'

In [3]:
# load model
trainer = Trainer(opts)
print('trainer initialized...')

DEBUG MODE
update options for debug purposes...
1234 is the seed!
learning rate: 0.0001
batch size is: 2
accumulate steps is: 4
effective batch size is: 8
Using DoMoRA


/mnt/cluster/workspaces/jinjingxu/proj/UniSfMLearner/submodule/Endo_FASt3r/trainer_end_to_end.py:311: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  depth_model_dict = torch.

DARES_MoDoRA


/mnt/cluster/environments/jinjingxu/pkg/envs/cu12/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


DoRA params initialized!
DoRA rank is: [14, 14, 12, 12, 10, 10, 8, 8, 8, 8, 8, 8]
DAM mora rank is  [14, 14, 12, 12, 10, 10, 8, 8, 8, 8, 8, 8]
Vector MoRA params initialized!
MoDoRA in Depth model
loaded endofast3r_depth_trained_dbg depth model...


/mnt/cluster/workspaces/jinjingxu/proj/UniSfMLearner/submodule/Endo_FASt3r/trainer_end_to_end.py:350: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.models["position_enc

CHECK: NO self.opt.predictive_mask
Model: depth_model
  Total params: 24981153 (23.82 MB)
  Total params trainable: 2933793 (2.80 MB)
Model: position_encoder
  Total params: 11698920 (11.16 MB)
  Total params trainable: 11698920 (11.16 MB)
Model: position
  Total params: 3154888 (3.01 MB)
  Total params trainable: 3154888 (3.01 MB)
Model: motion_position_encoder
  Total params: 11698920 (11.16 MB)
  Total params trainable: 11698920 (11.16 MB)
Model: motion_position
  Total params: 3154888 (3.01 MB)
  Total params trainable: 3154888 (3.01 MB)
Model: transform_encoder
  Total params: 11698920 (11.16 MB)
  Total params trainable: 11698920 (11.16 MB)
Model: transform
  Total params: 3157052 (3.01 MB)
  Total params trainable: 3157052 (3.01 MB)
Model: pose_encoder
  Total params: 11698920 (11.16 MB)
  Total params trainable: 11698920 (11.16 MB)
Model: pose
  Total params: 1314572 (1.25 MB)
  Total params trainable: 1314572 (1.25 MB)
Total params: 82558233 (78.73 MB)
Total params trainable: 

/mnt/cluster/workspaces/jinjingxu/proj/UniSfMLearner/submodule/Endo_FASt3r/trainer_end_to_end.py:407: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.models["pose_encoder

Using dataset:
   endovis
There are 8 training items and 8 validation items

trainer initialized...


In [4]:
# opts.pose_model_type
trainer.opt.pose_model_type,trainer.opt.unireloc3r_pose_estimation_mode

('separate_resnet', 'vanilla_pose_head_regression')

In [12]:
# trainer = Trainer(opts)
self = trainer #Trainer(opts)


# trainer.train()
"""Run the entire training pipeline
"""
self.epoch = 0
self.step = 0
self.start_time = time.time()

#quick and convenient but confusing recontrooling!
# self.opt.min_depth = 10.0 #risky
# self.opt.min_depth = 0.1 #risky
# self.opt.max_depth = 150.0
# self.opt.gt_metric_rel_pose_as_estimates_debug = False

# trained fast3r
# depth: 0.2-0.3
# rel_pose_per_axis: 2e-4

with torch.no_grad():
    # for self.epoch in range(self.opt.num_epochs):
    # self.run_epoch(self.epoch)
    """Run a single epoch of training and validation
    """
    epoch = self.epoch
    print("Training")

    self.model_optimizer_0.zero_grad()# debug only: save_mem
    self.model_optimizer.zero_grad()# debug only: save_mem

    # for batch_idx, inputs in enumerate(self.train_loader):
    train_iter = iter(self.train_loader)
    inputs = next(train_iter)



    before_op_time = time.time()

    # position
    self.set_train_0()
    if self.opt.debug:
        self.freeze_params(keys = ['position_encoder'])#debug only to save_mem
    _, losses_0 = self.process_batch_0(inputs)
    self.model_optimizer_0.zero_grad()
    # losses_0["loss"].backward()#debug only
    torch.nn.utils.clip_grad_norm_(self.parameters_to_train_0, max_norm=1.0)
    self.model_optimizer_0.step()

    self.set_train()
    if self.opt.debug:
        self.freeze_params(keys = ['depth_model', 'pose', 'transform_encoder'])#debug only to save_mem
    outputs, losses= self.process_batch(inputs)
    self.model_optimizer.zero_grad()
    # losses["loss"].backward() #debug only
    torch.nn.utils.clip_grad_norm_(self.parameters_to_train, max_norm=1.0)
    self.model_optimizer.step()

    duration = time.time() - before_op_time

    # phase = batch_idx % self.opt.log_frequency == 0

    # # if phase:
    # # self.log_time(batch_idx, duration, losses["loss"].cpu().data)
    # self.log_time(0, duration, losses["loss"].cpu().data, losses_0["loss"].cpu().data, )
    # scalers_to_log = {
    #     "scalar/loss": losses["loss"],
    #     "scalar/loss_0": losses_0["loss"],
    #     # "scalar/trans_err": metric_errs["trans_err"].mean(),
    #     # "scalar/rot_err": metric_errs["rot_err"].mean()
    # }
    # for k, v in errs.items():
    #     print(f"scalar/{k}: {v}")
    #     scalers_to_log[f"scalar/{k}"] = v
    # concat_img, img_order_strs = self.log("train", inputs, outputs, scalers_to_log, compute_vis=True, online_vis=False)
    
    
    # Use the accumulated loss for logging (multiply back to show effective loss)
    # effective_loss = losses["loss"] * (self.opt.accumulate_steps / max(1, accumulate_step % self.opt.accumulate_steps))
    # self.log_time(batch_idx, duration, effective_loss.cpu().data)
    losses_to_log = {
        "loss": losses["loss"],
        "loss_0": losses_0["loss"],
    }
    errs_to_log = {}
    errs = self.compute_pose_metrics(inputs, outputs)
    for k, v in errs.items():
        assert len(v) == len(self.opt.frame_ids)-1, f'{k}: {v}'
        # v is a list of torch tensors, average over them
        errs_to_log[f"{k}"] = torch.mean(torch.stack(v)).item()

    self.log_time(self.step, duration, losses["loss"].cpu().data, losses_0["loss"].cpu().data, 
                    errs_to_log)
    scalers_to_log = {**losses_to_log, **errs_to_log}
    scalers_to_log = {f"scalar/{k}": v for k, v in scalers_to_log.items()}    
    # #compute_pose_err
    for k, v in errs.items():
        print(f"{k}: {v}")

    # print('trans_err:', outputs[("trans_err", 0)])
    # print('rot_err:', outputs[("rot_err", 0)])

 

    # concat_img, img_order_strs = self.log("train", inputs, outputs, 
    concat_img_list, img_order_strs_list = self.log("train", inputs, outputs, 
                scalers_to_log, 
                compute_vis=True)

    import os, cv2
    save_path = "/mnt/cluster/workspaces/jinjingxu/proj/UniSfMLearner/submodule/Endo_FASt3r/"
    for concat_img, img_order_strs in zip(concat_img_list, img_order_strs_list):
    # concat_img, img_order_strs = self.log("train", inputs, outputs, 

        # remove the first char before the first _
        # img_order_strs = img_order_strs.split('_')[1:]
        # img_order_strs = '_'.join(img_order_strs)
        full_save_path = os.path.join(save_path, f"{img_order_strs}.png")
        cv2.imwrite(full_save_path, concat_img)
        print(f"saved train_concat_img.png in {full_save_path}")

    self.step += 1
    
    # break
        
    self.model_lr_scheduler.step()
    self.model_lr_scheduler_0.step()

    # if (self.epoch + 1) % self.opt.save_frequency == 0:
    #     self.save_model()
    # break
    


    # depth dim:
    # 256 320
    # 128,160,  
    # 64,80,
    # 32 40    # ===we go for this



# 0.06 0.04 0.04

Training
////frame_id as src: -1
gt_tgt2src_rel_poses trans:
tensor([[-0.2108,  0.3493, -0.0364],
        [-0.0121, -0.0086, -0.1336]], device='cuda:0')
pred_rel_poses_batch trans:
tensor([[ 4.4339e-04,  1.2005e-03,  3.5292e-04],
        [-6.1490e-05, -1.0257e-04, -4.7942e-04]], device='cuda:0')
////frame_id as src: 1
gt_tgt2src_rel_poses trans:
tensor([[ 0.0868, -0.2566,  0.0505],
        [ 0.0143,  0.0159,  0.1047]], device='cuda:0')
pred_rel_poses_batch trans:
tensor([[-3.4912e-04, -9.3808e-04,  1.4232e-04],
        [ 1.4375e-04, -1.3884e-05,  4.9114e-04]], device='cuda:0')
Report all metrics:
trans_err_ang_deg: [tensor(32.0934, device='cuda:0'), tensor(26.1969, device='cuda:0')]
trans_err_scale: [tensor(0.2714, device='cuda:0'), tensor(0.1906, device='cuda:0')]
rot_err_deg: [tensor(0.1707, device='cuda:0'), tensor(0.1093, device='cuda:0')]
pred_rel_trans_scale: [tensor(0.0009, device='cuda:0'), tensor(0.0008, device='cuda:0')]
pred_f0_depth_scale: [tensor(0.2546, device='cuda:0'), 

In [17]:
# 97 -16 -43

In [18]:

# self.set_eval()
# try:
#     # inputs = self.val_iter.next()
#     inputs = next(self.val_iter)
# except StopIteration:
#     self.val_iter = iter(self.val_loader)
#     inputs = self.val_iter.next()

# with torch.no_grad():
#     # outputs, losses = self.process_batch_val(inputs)
#     """Pass a minibatch through the network and generate images and losses
#     """
#     for key, ipt in inputs.items():
#         inputs[key] = ipt.to(self.device)

#     if self.opt.pose_model_type == "shared":
#         # If we are using a shared encoder for both depth and pose (as advocated
#         # in monodepthv1), then all images are fed separately through the depth encoder.
#         print('CHECK: self.opt.pose_model_type == "shared"')
#         all_color_aug = torch.cat([inputs[("color_aug", i, 0)] for i in self.opt.frame_ids])
#         all_features = self.models["encoder"](all_color_aug)
#         all_features = [torch.split(f, self.opt.batch_size) for f in all_features]

#         features = {}
#         for i, k in enumerate(self.opt.frame_ids):
#             features[k] = [f[i] for f in all_features]

#         outputs = self.models["depth"](features[0])
#     else:
#         print('CHECK: self.opt.pose_model_type != "shared"')
#         # Otherwise, we only feed the image with frame_id 0 through the depth encoder
#         features = self.models["encoder"](inputs["color_aug", 0, 0])
#         outputs = self.models["depth"](features)

#     if self.opt.predictive_mask:
#         outputs["predictive_mask"] = self.models["predictive_mask"](features)

#     if self.use_pose_net:
#         outputs.update(self.predict_poses(inputs, features, outputs))

#     self.generate_images_pred(inputs, outputs)
#     losses = self.compute_losses_val(inputs, outputs)

#     # return outputs, losses

#     self.log("val", inputs, outputs, losses)
#     del inputs, outputs, losses